# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.provision "shell", path: "script.sh"
  config.vm.provider :virtualbox do |v|
    v.name = "hadoop-cdh4-v2"
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.network :private_network, ip: "192.168.56.102"
end

# Useful urls:
